
services:
  
  app:
    build: .
    environment:
      - BOTSECRET=${BOTSECRET}
      - APPID=${APPID}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./sona-nyl.cn.pem:/etc/nginx/ssl/sona-nyl.cn.pem
      - ./sona-nyl.cn.key:/etc/nginx/ssl/sona-nyl.cn.key
    depends_on:
      - app
    restart: unless-stopped
  